import os
import re
import enum
import json
import numpy as np
import pandas as pd
import sqlalchemy as db

from opencell import constants
from opencell.database import models, utils
from opencell.imaging.processors import FOVProcessor


class MicroscopyFOVOperations:
    '''
    Methods to insert metadata associated with, or 'children' of, microscopy FOVs

    FOV-associated metadata includes the raw tiff metadata, FOV features, and thumbnails,
    FOV 'children' include the ROIs cropped from each FOV

    NOTE: instances of this class cannot be associated with instances of models.MicroscopyFOV
    (in the way that, for example, PolyclonalLineOperations instances
    are associated with instances of models.CellLine)
    because they may be passed to dask.delayed-wrapped methods

    '''

    def __init__(self, fov_id):
        self.fov_id = fov_id

    def insert_nothing(self, session, result):
        '''
        Placeholder method with the same signature as all of the `insert_*` methods
        '''
        return


    def insert_raw_tiff_metadata(self, session, result):
        '''
        Insert the raw tiff metadata and raw TIFF processing events
        generated by FOVProcessor.process_raw_tiff

        Parameters
        ----------
        result : dict with 'metadata' and 'events' keys
            (this should be the output of FOVProcessor.process_raw_tiff)
        '''

        result = utils.to_jsonable(result)
        metadata = result.get('metadata')
        events = result.get('events')

        row = models.MicroscopyFOVResult(
            fov_id=self.fov_id, kind='raw-tiff-metadata', data=metadata
        )
        utils.add_and_commit(session, row, errors='raise')

        if len(events):
            row = models.MicroscopyFOVResult(
                fov_id=self.fov_id, kind='raw-tiff-processing-events', data=events
            )
            utils.add_and_commit(session, row, errors='raise')


    def insert_fov_features(self, session, result):
        '''
        Insert FOV features
        result : dict returned by FOVProcessor.calculate_fov_features
        '''
        result = utils.to_jsonable(result)
        row = models.MicroscopyFOVResult(
            fov_id=self.fov_id, kind='fov-features', data=result
        )
        utils.add_and_commit(session, row, errors='raise')


    def insert_fov_thumbnails(self, session, result):
        '''
        Insert FOV thumbnails
        result : dict returned by FOVProcessor.generate_fov_thumbnails
        '''
        result = utils.to_jsonable(result)

        rows = []
        for channel, encoded_im in result['encoded_ims'].items():
            row = models.MicroscopyThumbnail(
                fov_id=self.fov_id,
                size=result['size'],
                channel=channel,
                data=encoded_im
            )
            rows.append(row)
        utils.add_and_commit(session, rows, errors='raise')


    def insert_roi_thumbnails(self, session, result):
        '''
        Insert ROI thumbnails for an ROI from the FOV
        result : dict returned by FOVProcessor.generate_roi_thumbnails
        '''

        # if there's no result, we assume the FOV did not an ROI
        if result is None:
            return

        result = utils.to_jsonable(result)

        rows = []
        for channel, encoded_im in result['encoded_ims'].items():
            row = models.MicroscopyThumbnail(
                roi_id=result['roi_id'],
                size=result['size'],
                channel=channel,
                data=encoded_im
            )
            rows.append(row)
        utils.add_and_commit(session, rows, errors='raise')


    def insert_z_profiles(self, session, result):
        '''
        Insert z-profiles
        result : dict returned by FOVProcessor.calculate_z_profiles
        '''
        result = utils.to_jsonable(result)
        row = models.MicroscopyFOVResult(
            fov_id=self.fov_id, kind='z-profiles', data=result
        )
        utils.add_and_commit(session, row, errors='raise')


    def insert_clean_tiff_metadata(self, session, result):
        '''
        Insert result from the generate_clean_tiff method
        '''
        result = utils.to_jsonable(result)
        row = models.MicroscopyFOVResult(
            fov_id=self.fov_id, kind='clean-tiff-metadata', data=result
        )
        utils.add_and_commit(session, row, errors='raise')


    def insert_corner_rois(self, session, result):
        '''
        Insert the four ROIs cropped from each corner of an FOV
        '''
        self._insert_rois(session, result, roi_kind='corner')


    def insert_annotated_roi(self, session, result):
        '''
        Insert the single manually-annotated ROI (if any)
        '''
        self._insert_rois(session, result, roi_kind='annotated')


    def _insert_rois(self, session, result, roi_kind):
        '''
        result : tuple of (error_info, roi_props) returned by FOVProcessor.crop_rois
        roi_kind : 'corner' or 'annotated'
        '''

        # FOVProcessor.crop_annotated_roi returns None if no manual annotation existed
        if result is None:
            return

        result, all_roi_props = result
        result = utils.to_jsonable(result)
        result_kind = '%s-roi-cropping' % roi_kind

        row = models.MicroscopyFOVResult(
            fov_id=self.fov_id, kind=result_kind, data=result
        )
        utils.add_and_commit(session, row, errors='raise')

        rois = []
        for roi_props in all_roi_props:
            roi_props = utils.to_jsonable(roi_props)
            roi = models.MicroscopyFOVROI(
                fov_id=self.fov_id, kind=roi_kind, props=roi_props
            )
            rois.append(roi)
        utils.add_and_commit(session, rois, errors='raise')
