import pandas as pd
from flask_restful import Resource

from flask import (
    current_app, 
    jsonify, 
    request
)

from opencell.database import models, operations
from opencell.api.cache import cache


class Plates(Resource):

    def get(self):
        '''
        All plate designs/instances
        '''
        raise NotImplementedError

    def post(self):
        '''
        Create a new plate design or instance
        '''
        raise NotImplementedError


class Plate(Resource):

    def get(self, plate_id):
        '''
        Get a plate design by design_id
        '''
        plate = current_app.Session.query(models.PlateDesign)\
            .filter(models.PlateDesign.design_id==plate_id)\
            .first()

        targets = [d.target_name for d in plate.crispr_designs]
        
        return {
            'plate_id': plate.design_id,
            'targets': targets,
        }

    
    def put(self, plate_id):
        '''
        Modify an existing plate design or instance
        '''
        raise NotImplementedError


class Electroporations(Resource):

    def get(self):
        '''
        Show all extant electroporations
        '''
        eps = current_app.Session.query(models.Electroporation).all()

        eps = [{
                'date': str(ep.electroporation_date), 
                'plate_id': ep.plate_instance.plate_design_id
            } for ep in eps]

        eps = sorted(eps, key=lambda d: d['plate_id'])
        return eps


    def post(self):
        '''
        Create a new electroporation
        '''
        raise NotImplementedError


class PolyclonalLines(Resource):


    @staticmethod
    def simplify_scalars(d):
        '''
        Simplify a dict of scalar values
        '''
        for key, value in d.items():
            if value is not None and not isinstance(value, str):
                d[key] = '%0.2f' % value
        return d

    @staticmethod
    def simplify_facs_histograms(histograms):
        '''
        Downsample and discretize the FACS histograms for a cell line
        This is intended to reduce the payload size when the histograms 
        will only be used to generate thumbnail/sparkline-like plots

        Note that the scaling, rounding, and 2x-subsampling were empirically determined
        as the most extreme downsampling that still yields satisfactory thumbnail-sized plots
        ('thumbnail-sized' means plots on the order of 100px wide)
        '''

        # x-axis values can be safely rounded to ints
        histograms['x'] = [int(val) for val in histograms['x']]

        # y-axis values (densities) must be scaled 
        scale_factor = 1e6
        for key in 'y_sample', 'y_ref_fitted':
            histograms[key] = [int(val*scale_factor) for val in histograms[key]]

        # finally, downsample by 2x
        for key in histograms.keys():
            histograms[key] = histograms[key][::2]

        return histograms


    @cache.cached(timeout=3600)
    def get(self):
        '''
        All polyclonal lines 
        (that is, all lines directly generated by an electroporation)
        '''

        eps = current_app.Session.query(models.Electroporation).all()

        line_data = []
        for ep in eps[:]:
            for line in ep.electroporation_lines:
                
                # get the crispr design for this line
                for design in ep.plate_instance.plate_design.crispr_designs:
                    if design.well_id==line.well_id:
                        break

                # the crispr design
                # (includes plate design id and well_id)
                d = design.as_dict()

                # append cell-line- and electroporation-specific fields 
                d['cell_line_id'] = line.cell_line_id
                d['plate_instance_id'] = ep.plate_instance_id
                d['electroporation_date'] = ep.electroporation_date

                # the facs results (scalars and histograms)
                # TODO: enforce one-to-one and drop the [0]
                d['facs_results'], d['facs_histograms'] = {}, {}
                if line.cell_line.facs_results:
                    facs_results = line.cell_line.facs_results[0].as_dict()
                    d['facs_histograms'] = self.simplify_facs_histograms(facs_results.pop('histograms'))    
                    d['facs_results'] = self.simplify_scalars(facs_results)

                # the sequencing ratios
                d['sequencing_results'] = {}
                if line.cell_line.sequencing_results:
                    d['sequencing_results'] = self.simplify_scalars(
                        line.cell_line.sequencing_results[0].as_dict())
                    
                line_data.append(d)
        
        return jsonify(line_data[:])


class FACSHistograms(Resource):

    def get(self, cell_line_id):
        '''
        The FACS histograms for a given cell_line_id
        '''
        
        facs_results = current_app.Session.query(models.FACSResult).filter(
            models.FACSResult.cell_line_id==cell_line_id
        ).first()

        if facs_results:
            d = {}
            for key, value in facs_results.histograms.items():
                d[key] = value[::2]
            return jsonify(d)
        else:
            return None

        # # coerce to ints to save space
        # facs['histograms']['x'] = [
        #     int(val) for val in facs['histograms']['x']]
        # facs['histograms']['y_sample'] = [
        #     int(val*1e6) for val in facs['histograms']['y_sample']]
        # facs['histograms']['y_ref_fitted'] = [
        #     int(val*1e6) for val in facs['histograms']['y_ref_fitted']]
