import os
import pandas as pd
import sqlalchemy as db

from flask_restful import Resource, reqparse
from flask import (
    current_app, 
    jsonify, 
    request,
    send_file,
)

from opencell.imaging.processors import FOVProcessor
from opencell.database import models, operations
from opencell.api.cache import cache


class Plates(Resource):

    def get(self):
        '''
        All plate designs/instances
        '''
        raise NotImplementedError

    def post(self):
        '''
        Create a new plate design or instance
        '''
        raise NotImplementedError


class Plate(Resource):

    def get(self, plate_id):
        '''
        Get a plate design by design_id

        TODO: handle invalid plate_id (what error code to return?)
        '''
        plate = current_app.Session.query(models.PlateDesign)\
            .filter(models.PlateDesign.design_id == plate_id)\
            .first()

        targets = [d.target_name for d in plate.crispr_designs]
        
        return {
            'plate_id': plate.design_id,
            'targets': targets,
        }

    
    def put(self, plate_id):
        '''
        Modify an existing plate design or instance
        '''
        raise NotImplementedError


class Electroporations(Resource):

    def get(self):
        '''
        Show all extant electroporations
        '''
        eps = current_app.Session.query(models.Electroporation).all()

        eps = [{
                'date': str(ep.electroporation_date), 
                'plate_id': ep.plate_instance.plate_design_id
            } for ep in eps]

        eps = sorted(eps, key=lambda d: d['plate_id'])
        return eps


    def post(self):
        '''
        Create a new electroporation
        '''
        raise NotImplementedError


class PolyclonalLines(Resource):

    @cache.cached(timeout=1)
    def get(self):
        '''
        All polyclonal lines 
        (that is, all lines directly generated by an electroporation)
        '''

        args = request.args
        kind = args.get('kind')
        target_name = args.get('target_name')

        if kind is not None and kind not in ['all', 'facs', 'sequencing', 'ms', 'microscopy']:
            # TODO: return the right http error
            pass

        lines = []
        if target_name:
            cds = current_app.Session.query(models.CrisprDesign)\
                .filter(db.func.lower(models.CrisprDesign.target_name)\
                .startswith(target_name.lower())).all()
            for cd in cds:
                ep_lines = cd.plate_design.plate_instances[0].electroporations[0].electroporation_lines
                cell_lines = [line.cell_line for line in ep_lines if line.well_id == cd.well_id]
                lines.append(cell_lines[0])
        else:
            eps = current_app.Session.query(models.Electroporation).all()
            for ep in eps:
                lines.extend([ep_line.cell_line for ep_line in ep.electroporation_lines])

        # limit to the first ten lines to prevent returning giant payloads
        if kind is not None:
            lines = lines[:10] if len(lines) > 10 else lines
    
        data = []
        for line in lines:
            ops = operations.PolyclonalLineOperations.from_line_id(current_app.Session, line.id)
            data.append(ops.construct_json(kind=kind))
        return jsonify(data)


class PolyclonalLine(Resource):

    def get(self, cell_line_id):
        '''
        '''
        ops = operations.PolyclonalLineOperations.from_line_id(current_app.Session, cell_line_id)
        return jsonify(ops.construct_json())


class MicroscopyFOV(Resource):

    def get(self, fov_id, channel, kind):
        
        # hard-coded for z-projections (and not x- or y-)
        if kind == 'proj':
            ext = 'tif'
        elif kind == 'nrrd':
            ext = 'nrrd'
        else:
            # TODO: return 404
            pass
    
        fov = current_app.Session.query(models.MicroscopyFOV)\
            .filter(models.MicroscopyFOV.id == fov_id).first()

        processor = FOVProcessor.from_database(fov)
        filepath = processor.dst_filepath(
            dst_root=current_app.config.get('opencell_microscopy_root'), 
            kind=kind, 
            channel=channel, 
            ext=ext)
    
        filename = filepath.split(os.sep)[-1]

        return send_file(
            open(filepath, 'rb'),
            as_attachment=True, 
            attachment_filename=filename)


class FACSHistograms(Resource):

    def get(self, cell_line_id):
        '''
        The FACS histograms for a given cell_line_id
        '''
        
        facs_result = current_app.Session.query(models.FACSResult).filter(
            models.FACSResult.cell_line_id == cell_line_id
        ).first()

        if facs_result:
            d = {}
            for key, value in facs_result.histograms.items():
                d[key] = value[::2]
            return jsonify(d)
        else:
            return None

        # # coerce to ints to save space
        # facs['histograms']['x'] = [
        #     int(val) for val in facs['histograms']['x']]
        # facs['histograms']['y_sample'] = [
        #     int(val*1e6) for val in facs['histograms']['y_sample']]
        # facs['histograms']['y_ref_fitted'] = [
        #     int(val*1e6) for val in facs['histograms']['y_ref_fitted']]
