"""add embedding-related tables

Revision ID: 93ae3f97278a
Revises: 0cd142e454aa
Create Date: 2021-01-13 15:08:52.465209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93ae3f97278a"
down_revision = "0cd142e454aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cell_line_embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("grid_size", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cell_line_embedding")),
        sa.UniqueConstraint("name", "grid_size", name=op.f("uq_cell_line_embedding_name")),
    )
    op.create_table(
        "thumbnail_tile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thumbnail_size", sa.Integer(), nullable=False),
        sa.Column("thumbnail_shape", sa.String(), nullable=False),
        sa.Column("tile_filename", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thumbnail_tile")),
    )
    op.create_table(
        "cell_line_embedding_position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("embedding_id", sa.Integer(), nullable=True),
        sa.Column("cell_line_id", sa.Integer(), nullable=True),
        sa.Column("position_x", sa.Float(), nullable=False),
        sa.Column("position_y", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cell_line_id"],
            ["cell_line.id"],
            name=op.f("fk_cell_line_embedding_position_cell_line_id_cell_line"),
        ),
        sa.ForeignKeyConstraint(
            ["embedding_id"],
            ["cell_line_embedding.id"],
            name=op.f("fk_cell_line_embedding_position_embedding_id_cell_line_embedding"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cell_line_embedding_position")),
    )
    op.create_table(
        "thumbnail_tile_position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tile_id", sa.Integer(), nullable=True),
        sa.Column("cell_line_id", sa.Integer(), nullable=True),
        sa.Column("tile_row", sa.Integer(), nullable=False),
        sa.Column("tile_column", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cell_line_id"],
            ["cell_line.id"],
            name=op.f("fk_thumbnail_tile_position_cell_line_id_cell_line"),
        ),
        sa.ForeignKeyConstraint(
            ["tile_id"],
            ["thumbnail_tile.id"],
            name=op.f("fk_thumbnail_tile_position_tile_id_thumbnail_tile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thumbnail_tile_position")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thumbnail_tile_position")
    op.drop_table("cell_line_embedding_position")
    op.drop_table("thumbnail_tile")
    op.drop_table("cell_line_embedding")
    # ### end Alembic commands ###
