"""edits to embedding-related tables

Revision ID: bedce04cf1d3
Revises: 93ae3f97278a
Create Date: 2021-01-13 19:42:31.658244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bedce04cf1d3"
down_revision = "93ae3f97278a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("thumbnail_tile", sa.Column("filename", sa.String(), nullable=False))
    op.create_unique_constraint(op.f("uq_thumbnail_tile_filename"), "thumbnail_tile", ["filename"])
    op.drop_column("thumbnail_tile", "tile_filename")
    op.drop_column("thumbnail_tile", "thumbnail_size")
    op.drop_column("thumbnail_tile", "thumbnail_shape")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "thumbnail_tile",
        sa.Column("thumbnail_shape", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "thumbnail_tile",
        sa.Column("thumbnail_size", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "thumbnail_tile",
        sa.Column("tile_filename", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_thumbnail_tile_filename"), "thumbnail_tile", type_="unique")
    op.drop_column("thumbnail_tile", "filename")
    # ### end Alembic commands ###
